version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
